### ISSUE TITLE
Is there a way to filter devices to enable only specific devices?

### ISSUE THREAD

**Issue by rxin** [langovoi/homebridge-upnp#3]
First - awesome plugin. I have it installed and now finally I can use it to control my TV and Sonos volume.

I have multiple upnp devices and it's quite annoying to have all of them show up. Is there a way I can specify a list of devices I want to show up in HomeKit? Thanks.

**Comment by langovoi** [comment]
Glad to see you like my plugin!

Sure, I will make exclude option for config in next version.

Could you provide devices list (full model name) which you successfully used with plugin?
It need for list of supported and tested devices which I prepare.

**Comment by rxin** [comment]
I have a Samsung NU8000 TV wired to a Sonos Beam using HDMI ARC, with two Sonos Play 1s.  This works well for the Sonos Beam. It doesn't work for the NU8000 TV (it shows as no response whenever I changed the volume), possibly because the TV is connected to Sonos Beam and as a result TV's own speaker is disabled. That's why I want to exclude the TV from showing up in the list.

**Comment by langovoi** [comment]
I added `excludeUSN` option for config, see readme for more info.

**Comment by rxin** [comment]
Confirm that this works. Thanks!
