### ISSUE TITLE
Uninstalled, all references in config.json removed. Devices still showing

### ISSUE THREAD

**Issue by bubffm** [langovoi/homebridge-upnp#6]
behaviour as described. I have uninstalled homebridge-upnp, no longer shows in list of plugins, 
edited config Jason to remove reference to the modul, but I still get a full list of upnp devices showing up in Homekit.

Any idea how to fix?

**Comment by davic80** [comment]
Run homebridge -D -R

**Comment by langovoi** [comment]
Hope @davic80's comment was helpful
